# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Belgium 2014"
email: "bru-gtug@googlegroups.com"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/DevFest2014"
url: "http://gdg-brussels.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA"
googleAnalyticsSiteUrl: "gdg-brussels.org"

# Organizer Info
organizerName: "GDG Brussels"
organizerAlternateName: "Google Developer Group Brussels"
organizerDescription: "The Google Developer Group Brussels is an English speaking group meeting in Brussels to discuss Google Technologies with focus on developing and software."
organizerEmail: "bru-gtug@googlegroups.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdg-brussels.org"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, polymer, dart, design, developers, belgium, brussels"
twitterAccount: "@pjv_"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/devfestBE2014c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/practical/", text: "Practical"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "http://bit.ly/devfestBE2014c4p", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "http://bit.ly/devfestBE2014c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout> 2014"
eventDate: "November 9th and 15th, 2014"
typeoutTextValues: '"", "Season", "Belgium", "Brussels"'
typeoutFallback: "Belgium"
heroButtons:
 - {link: "http://bit.ly/devfestBE2014c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Register"}

# About Block
aboutTitle: "About GDG DevFest Belgium"
aboutBlock:
 - {title: "Dart", image: "dart.jpg", text: "DayOne<br><b>November 9th</b><br>Before Devoxx" }
 - {title: "Android Wear", image: "androidwear.png", text: "" }
 - {title: "Polymer", image: "polymer.jpg", text: "DayTwo<br><b>November 15th</b><br>After Devoxx" }
aboutBlock2:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lot's of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Workshops, hands-on experience, hacking and debugging. Come and pick up a new skill!" }
 - {title: "Design", image: "design.jpg", text: "Get creative and work with the newest design guidelines. " }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "50", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "15", specialCharacter: "+", info: "hours", detail: "of modern technologies"}
 - {count: "5", specialCharacter: "+", info: "speakers", detail: "from Belgium and beyond"}
 - {count: "2", specialCharacter: "", info: "tracks", detail: "over 2 separate days"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
#rockstarSpeakersImage: "rockstar-speakers.jpg"
#rockstarSpeakersCount: 4
#rockstarSpeakersTitle: "Rockstar speakers"
#rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location DayOne"
eventLocationName: "Eureka Secretariat"
eventLocationLink: "https://plus.google.com/117442528406997774839/about"
eventStreetAddress: "Neerveldstraat 107"
eventAddressLocality: "Brussels"
eventPostalCode: "1200"
eventAddressCountry: "Belgium"
eventStartTime: "2014-11-09T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-11-09T19:00"
eventPlaceCoordinates: "50.852676, 4.442194"
mapCenterCoordinates: "50.7141534, 5.8035117"
mapMobileCenterCoordinates: "50.852676, 4.442194"

# Location Block
locationBlockTitle2: "Location DayTwo"
eventLocationName2: "Google Belgium"
eventLocationLink2: "https://plus.google.com/+GoogleBelgiumBruxelles/about"
eventStreetAddress2: "Chaussée d'Etterbeek 180"
eventAddressLocality2: "Brussels"
eventPostalCode2: "1040"
eventAddressCountry2: "Belgium"
eventStartTime2: "2014-11-15T10:00"
eventDoorTime2: "09:00"
eventEndTime2: "2014-11-15T19:00"
eventPlaceCoordinates2: "51.852676, 4.442194"
mapCenterCoordinates2: "51.7141534, 5.8035117"
mapMobileCenterCoordinates2: "51.852676, 4.442194"

# Venue Block #TODO
#venueBlockTitle: "Venue"
#venueBigImage: "venue_0.jpg"
#venueSmallImage1: "venue_1.jpg"
#venueSmallImage2: "venue_2.jpg"
#venueSmallImage3: "venue_3.jpg"
#venueTitle: "Kinopalace Cinema"
#venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block #TODO
#tweetsFeedImage: "twitter-feed.jpg"
#tweetsFeedTitle: "What's Up?"
#twitterHashTag: "devfest"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block #TODO
#subscribeImage: "subscribe.jpg"
#subscribeTitle: "Subscribe for updates"
#subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
#subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Sign-up"
ticketsInfo: "Lunch included."
ticketsOffers:
 -
  name: "Free access (DayOne 9th)"
  ticketsNumber: "50"
  buyButtonLink: "http://www.meetup.com/gdg-brussels/events/212022342/"
  buyButtonText: "Sign Up Now"
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-11-08T23:59"
 -
  name: "Free access (DayTwo 15th)"
  ticketsNumber: "50"
  buyButtonLink: "http://www.meetup.com/gdg-brussels/events/212023862/"
  buyButtonText: "Sign Up Now"
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-11-14T23:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/105068877693379070381", icon: "google-plus"}
# - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"} #TODO
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
# - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://plus.google.com/105068877693379070381", text: "GDG Brussels on Google+"}
   - {link: "http://gdg-brussels.org", text: "GDG-Brussels.org"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contact"
  links:
   - {link: "mailto:bru-gtug@googlegroups.com", text: "bru-gtug@googlegroups.com"}#TODO

# Blog #TODO
#blogTitle: "Latest news"
#blogCommentsEnabled: true
#discusShortName: "devfestua"

# Speakers List Block
showSessions: false #TODO

# Team Block #TODO
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block #TODO
findWayTitle: "Find your way to Eureka Secretariat (DayOne)"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "50.7141534, 5.8035117"
logisticsMapMobileCenterCoordinates: "50.852676, 4.442194"

# Logistics Find Way2 Block #TODO
findWayTitle2: "Find your way to Google Belgium (DayTwo)"
findWayDistance2: "Distance"
findWayDriving2: "DRIVING"
findWayWalking2: "WALKING"
findWayBicycling2: "BICYCLING"
findWayTransit2: "TRANSIT"
findWayFindFlight2: "Find Flight"
logisticsMapCenterCoordinates2: "51.7141534, 5.8035117"
logisticsMapMobileCenterCoordinates2: "51.852676, 4.442194"

# Logistics Direction Details Block #TODO
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards: 
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   - 
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
#hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
#aboutHackathonTitle: "Meet our themes"
#hackathonRows:
# - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
# - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
# - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
#judgesImage: "judges.jpg"
#judgesTitle: "Judges"

# Hackathon Prizes Block
#prizesTitle: "Prizes"
#prizes:
# - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
# - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
# - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
#hackathonLocationBlockTitle: "Location"
#hackathonLocationName: "Communa"
#hackathonLocationLink: "http://communa.net.ua/"
#hackathonStreetAddress: "1 Halytska St"
#hackathonAddressLocality: "Lviv"
#hackathonAddressLocalityRegion: "Lvivska"
#hackathonPostalCode: "79000"
#hackathonAddressCountry: "Ukraine"
#hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
#hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
#viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"